### ISSUE TITLE
Integrating with upstart

### ISSUE THREAD

**Issue by laher** [facebookgo/grace#17]
Hi there. Gracehttp is restarting beautifully, but I can't figure out a way to make it work with Upstart. Once the original process stops, Upstart loses track of the process and reports it as 'not working'. I've spent a fair few hours meddling with settings, and I've tried calling start-stop-daemon (with --name and --startas instead of --pidfile), but to no avail.

Do you have any recommendations, or do you know anyone who's got it working?

Thanks

**Comment by vastbinderj** [comment]
http://upstart.ubuntu.com/cookbook/#reload-signal

in your case 

       reload signal USR2

**Comment by daaku** [comment]
The problem with Upstart (and other similar systems) is that they don't expect the PID of the process to change after it has been started. `grace` breaks this because it starts a new process (while the old one finishes it's work) which has a new PID. There are ways to work around this, but we found they increase complexity in what is already a complex process. One solution that I haven't tried myself is what https://github.com/rcrowley/goagain does with it's experimental "`Double` strategy". It works by doing _two_ restarts instead of one where the second restart is an `Exec` in the PID of the original process after it has finished doing it's work. You could in theory build this using the `gracenet` and the `httpdown` packages (that is your own version of the `gracehttp` package).

**Comment by aviflax** [comment]
Is there a recommended alternative to Upstart and systems like it?

**Comment by daaku** [comment]
I'm guessing there are a lot of opinions on that, but the one we use at Parse is https://mmonit.com/monit/ combined with https://github.com/facebookgo/pidfile (actually wrapped with https://github.com/facebookgo/cmdctrl).

**Comment by laher** [comment]
Thanks guys. Unfortunately @vastbinderj, the reload signal doesn't complete the picture. The graceful restart itself works a treat, but after that point, Upstart treats the service as 'stopped'. @daaku 's first comment explains the problem. Also we have respawn switched on, so Upstart tries to relaunch over & over.

@daaku thanks for the tip with goagain. Unfortunately the `Double` strategy has been marked as 'experimental', and there seems to be a slim possibility of clashing PIDs, but it's certainly an interesting thought. 

I was also thinking of setting up a double-restart, but the idea was slightly different. Assuming Upstart  `respawn`s a new executable, I could let it start, distinguish the 2 processes via grace's environment variable, and then trigger another handoff once the new app comes up. IPC could be handled via a local port Listened by the intermediate [grace] process. The intermediate process would stop listening as soon as it heard that the new upstart-derived process was ready to listen.

Having said all that, I guess monit (or maybe supervisor) is my best bet for now, but in the meantime I hope you re-visit the double-restart idea at some stage. Thanks for the advice.

**Comment by orivej** [comment]
My fork at https://github.com/orivej/grace reimplements `gracehttp` such that the original process never exits: it opens sockets and passes them to a child that servers them, terminates child on SIGTERM and replaces it with a new one on SIGUSR2. This is supposed to emulate what systemd would do with socket activation, and is compatible with expectations of Upstart. Under systemd with socket activation the emulation is skipped. (Although I did not yet check it under systemd.)

`gracenet` could be similarly reimplemented, but I did not touch so far.
