### ISSUE TITLE
Feature Request: gracehttp to serve with custom net.Listener's

### ISSUE THREAD

**Issue by garukun** [facebookgo/grace#23]
I think it'd be very useful to be able to have `gracehttp.Serve(servers...)` to take an additional argument for the custom `net.Listener` to use for handling low-level network connections. The method signature can look like:

```go
func ServeWith(l net.Listener, servers ...*http.Server) {
  // Implementation details.
}
```

I can make a PR for this if this sounds like an entertaining idea.

**Comment by daaku** [comment]
grace needs to _create_ the `net.Listener` because of how it works. What are you trying to do? You find using https://godoc.org/github.com/facebookgo/grace/gracenet directly and copying `gracehttp` a better option (it's barely any code and pretty specific to make the common http case simple to use).

**Comment by garukun** [comment]
I was looking for an option to limit incoming connections by prevent the underlying listener to accept connections when it reaches some limit, kinda like the [netutil.LimitListener](https://godoc.org/golang.org/x/net/netutil#LimitListener).

**Comment by daaku** [comment]
Yeah makes sense. I think you're better off using `gracenet` and wrapping the listener it returns and using it with the http library. I really want to keep `gracehttp` small and limited to the simple-ish use cases.
