### ISSUE TITLE
Any plan to support fasthttp?

### ISSUE THREAD

**Issue by yeka** [facebookgo/grace#25]
I've using [grace](https://github.com/facebookgo/grace) for my project together with [echo (v1)](https://github.com/labstack/echo). It works great and I love it 😃 
Since v2, echo add support for [fasthttp](https://github.com/valyala/fasthttp).
Switching between standard net/http and fasthttp is easy, but grace won't work with fasthttp.
Is there any plan to support fasthttp?

Would like to hear your feedback :)

**Comment by daaku** [comment]
`gracehttp` is the thing that provides the easy to use `net/http` logic. This is built on top of `gracenet` and `httpdown` -- the latter is specific to `net/http` in that it relies on https://golang.org/pkg/net/http/#ConnState to track active requests. You should be able to rely on `gracenet` since it's generic and works at the `net.Listener` level, but you'll need to build something like `httpdown` for `fasthttp` -- not sure how easy that is or if there are enough hooks for it. Happy to guide to through it, but I think it's best to have it be in a separate repo!
