### ISSUE TITLE
After a graceful restart, new process does not react on SIGTERM

### ISSUE THREAD

**Issue by flyingmutant** [facebookgo/grace#5]
Steps to reproduce (Go 1.1.2, OS X 10.8.5):
1) `gracedemo`
2) `curl 'http://localhost:48567/sleep/?duration=30s'`
3) `kill -USR2 $GRACEDEMOPID`
4) observe proper graceful restart; `curl 'http://localhost:48567/sleep/?duration=1s'` works fine
5) `kill $GRACEDEMOPID_NEW`
6) `gracedemo` process still alive; `curl 'http://localhost:48567/sleep/?duration=1s'` hangs

**Comment by nkev** [comment]
Now it only restarts once:

1) gracedemo
2) curl 'http://localhost:48567/sleep/?duration=30s'
3) kill -USR2 $GRACEDEMOPID
4) observe proper graceful restart; curl 'http://localhost:48567/sleep/?duration=1s' works fine
5) kill **-USR2** $GRACEDEMOPID_NEW
6) gracedemo process terminates instead of restarting
